version: '3.8'
services:
   wp_mysql:
     image: mysql:8
     container_name: wp_mysql
     ports:
       - "3336:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wpdb
       MYSQL_USER: wpuser
       MYSQL_PASSWORD: wppass
volumes:
    db_data: